# syntax=docker/dockerfile:1.20.0
ARG UPSTREAM_TAG
FROM docker.io/library/haproxy:${UPSTREAM_TAG} AS haproxy

USER root

# Needed to use auth-url & auth-signin with haproxy-ingress
RUN apt-get update && apt-get upgrade -y --no-install-recommends && \
    apt-get install -y --no-install-recommends lua-json=1.3.4-3 && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Rootless
USER haproxy
ENTRYPOINT ["/usr/local/sbin/haproxy"]