# syntax=docker/dockerfile:1.20.0

FROM --platform=${BUILDPLATFORM} ghcr.io/wiremind/base:hardened-systemd@sha256:40d2459e98bb2a4b9646b000e2d6c7af52b482f44864829647f3a5457f5691c1 AS builder

# hadolint ignore=DL3002
USER root
SHELL ["/bin/bash", "-exo", "pipefail", "-c"]

ARG TARGETARCH
ARG UPSTREAM_TAG

# hadolint ignore=SC2046
RUN <<-EOF
    # Let us choose among all versions
    echo "net-proxy/haproxy ~${TARGETARCH}" > /etc/portage/package.accept_keywords/haproxy
    # Use patched version of luajson
    # See https://github.com/gentoo-mirror/gentoo/blob/master/dev-lua/luajson/files/luajson-1.3.4-lpeg-1.1.patch
    echo "=dev-lua/luajson-1.3.4-r1 ~${TARGETARCH}" > /etc/portage/package.accept_keywords/luajson

    # Do not install uneeded things
    echo -e "\napp-eselect/eselect-lua-4-r1" >> /etc/portage/profile/package.provided
    echo -e "\napp-admin/eselect-1.4.30" >> /etc/portage/profile/package.provided
    # Disable gentoo haproxy user & group
    echo -e "\nacct-user/haproxy-0-r3" >> /etc/portage/profile/package.provided
    echo -e "\nacct-group/haproxy-0-r3" >> /etc/portage/profile/package.provided

    # System USE flags
    SYSTEM_USE="vanilla minimal -static -static-libs -ncurses -systemd -perl"

    # Minimal rootfs
    USE="build" emerge -1 --root=/rootfs sys-apps/baselayout
    USE="headers-only" emerge -1 --root=/rootfs sys-kernel/linux-headers
    USE="-cacert" emerge -1 --root=/rootfs app-misc/ca-certificates

    # HAProxy user & group
    # We manually set uid & gid to 99 to keep compatibility with haproxy-ingress
    echo "haproxy:x:99:99::/var/lib/haproxy:/sbin/nologin" >> /rootfs/etc/passwd
    echo "haproxy:x:99:" >> /rootfs/etc/group
    echo "haproxy:!:20430::::::" >> /rootfs/etc/shadow
    echo "haproxy:!::" >> /rootfs/etc/gshadow

    mkdir -p /rootfs/var/lib/haproxy && touch /rootfs/var/lib/haproxy/.empty
    chown -R 99:99 /rootfs/var/lib/haproxy

    # Build haproxy
    # /!\ haproxy-ingress uses lua5-3 (see https://github.com/jcmoraisjr/haproxy-ingress/blob/master/builder/Dockerfile)
    # NB: luajson (harningt/luajson) is needed to use auth-url & auth-signin with haproxy-ingress
    LUA_TARGETS="lua5-3" LUA_SINGLE_TARGET="lua5-3" \
    USE="${SYSTEM_USE} lua crypt -net_ns -pcre quic -slz ssl -systemd threads zlib" \
    emerge -1 --root=/rootfs dev-lua/lpeg dev-lua/luajson =net-proxy/haproxy-${UPSTREAM_TAG}

    # GCC shared libs
    mkdir -p /rootfs/$(gcc-config -L)
    cp $(gcc-config -L)/libgcc_s.so* /rootfs/$(gcc-config -L)/

    # Rebuild path cache for shared libs
    cp -r /etc/ld.so.conf* /rootfs/etc/
    ldconfig -r /rootfs

    # Clean up portage & system uneeded files
    rm -rf /rootfs/var/{cache,db,lib,log}/*
    rm -rf /rootfs/usr/share/{doc,eselect,info,i18n,man,readline,terminfo,vim,zoneinfo} /rootfs/usr/include
    find /rootfs -type f -name '*.[ao]' -delete
    find /rootfs -type f -name '*.pc' -delete
EOF

ENTRYPOINT ["/bin/bash"]


FROM --platform=${BUILDPLATFORM} scratch

WORKDIR /
COPY --from=builder /rootfs/ /

# Rootless
USER haproxy
WORKDIR /var/lib/haproxy

EXPOSE 8080/tcp
EXPOSE 8443/tcp

# Graceful stop
STOPSIGNAL SIGUSR1
HEALTHCHECK NONE

ENTRYPOINT ["/bin/haproxy"]