# syntax=docker/dockerfile:1.20.0

# This stage will download, verify and extract the stage3 tarball
FROM --platform=${BUILDPLATFORM} docker.io/library/debian:trixie AS builder

# hadolint ignore=DL3002
USER root
WORKDIR /gentoo
SHELL ["/bin/bash", "-exo", "pipefail", "-c"]

ARG TARGETARCH
ARG UPSTREAM_TAG
ARG TIMESTAMP="20260111T160052Z"
ARG DIST="https://distfiles.gentoo.org/releases/${TARGETARCH}/autobuilds/current-stage3-${TARGETARCH}-${UPSTREAM_TAG}"
ARG STAGE3="stage3-${TARGETARCH}-${UPSTREAM_TAG}-${TIMESTAMP}.tar.xz"
ARG STAGE3_URL="${DIST}/${STAGE3}"

# See https://wiki.gentoo.org/wiki/Handbook:AMD64/Installation/Stage
# hadolint ignore=DL3008
RUN <<-EOF
    # Install dependencies
    apt-get update
    apt-get upgrade -y
    apt-get install -y --no-install-recommends ca-certificates curl gnupg xz-utils

    # Setup GPG
    # See https://www.gentoo.org/downloads/signatures/
    curl -sfLo - "https://qa-reports.gentoo.org/output/service-keys.gpg" | gpg --import
    gpg --list-keys

    # Get stage3 files
    curl -s --remote-name-all "${STAGE3_URL}{,.CONTENTS.gz,.asc,.DIGESTS,.sha256}"

    # GPG check
    gpg --verify ${STAGE3}.asc
    gpg --verify ${STAGE3}.DIGESTS
    gpg --verify ${STAGE3}.sha256

    # Check image integrity
    openssl dgst -r -sha512 ${STAGE3}
    openssl dgst -r -blake2b512 ${STAGE3}
    sha256sum -c ${STAGE3}.sha256

    # Extract stage3
    tar xpf "${STAGE3}" --xattrs-include='*.*' --numeric-owner || true

    # Clean up
    rm -f ${STAGE3}*
EOF


# This stage will make a base gentoo toolchain workable
FROM --platform=${BUILDPLATFORM} scratch AS toolchain-nocustomized

WORKDIR /
COPY --from=builder /gentoo/ /

# hadolint ignore=DL3002
USER root
SHELL ["/bin/bash", "-exo", "pipefail", "-c"]

# Portage settings
# XXX COPY does not preserve empty directories...
RUN mkdir -p /var/db/repos/gentoo /var/{log,tmp}/portage

# Download portage tree
ONBUILD RUN emerge-webrsync --quiet

ENTRYPOINT ["/bin/bash"]