# syntax=docker/dockerfile:1.20.0

FROM --platform=${BUILDPLATFORM} docker.io/debian:${UPSTREAM_TAG}
USER root

ARG TARGETARCH
RUN <<-EOF
	apt-get update -y
	apt-get upgrade -y --no-install-recommends
	apt-get install curl coreutils -y
	apt-get clean
	useradd -m kubectluser
	KUBECTL_VERSION=$(curl -Ls https://dl.k8s.io/release/stable.txt)
	curl -LO https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/${TARGETARCH}/kubectl
	curl -LO https://dl.k8s.io/${KUBECTL_VERSION}/bin/linux/${TARGETARCH}/kubectl.sha256
	sha256sum --check ./kubectl.sha256
	chmod +x ./kubectl
	mv ./kubectl /usr/local/bin/kubectl
EOF

USER kubectluser
WORKDIR /home/kubectluser
