# syntax=docker/dockerfile:1.20.0

# hadolint global ignore=DL3008
FROM --platform=${BUILDPLATFORM} docker.io/debian:${UPSTREAM_TAG}
USER root

ARG TARGETARCH
RUN <<-EOF
	set -e
	apt-get update -y
	apt-get upgrade -y --no-install-recommends
	apt-get install coreutils -y --no-install-recommends
	apt-get install curl -y
	apt-get clean
	rm -rf /var/lib/apt/lists/*
	useradd -m kubectluser
	KUBECTL_VERSION="$(curl -Ls https://dl.k8s.io/release/stable.txt)"
	curl -LO "https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/${TARGETARCH}/kubectl"
	curl -LO "https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/${TARGETARCH}/kubectl.sha256"
	sed -i 's|$|  kubectl|' kubectl.sha256
	sha256sum --check ./kubectl.sha256
	chmod +x ./kubectl
	mv ./kubectl /usr/local/bin/kubectl
EOF

USER kubectluser
WORKDIR /home/kubectluser
