# syntax=docker/dockerfile:1.20.0

FROM --platform=${BUILDPLATFORM} docker.io/debian:trixie-slim

USER root
SHELL ["/bin/bash", "-exo", "pipefail", "-c"]

ARG UPSTREAM_TAG
ARG TARGETARCH

# hadolint ignore=DL3008
RUN <<-EOF
	apt-get update -y
	apt-get upgrade -y --no-install-recommends
	apt-get install -y --no-install-recommends coreutils curl ca-certificates

	apt-get clean
	rm -rf /var/lib/apt/lists/*

	curl -sL --remote-name-all "https://dl.k8s.io/release/${UPSTREAM_TAG}/bin/linux/${TARGETARCH}/kubectl{,.sha256}"

	sed -i 's|$|  kubectl|' kubectl.sha256
	sha256sum --strict --check kubectl.sha256

	chmod +x kubectl
	mv kubectl /usr/local/bin/kubectl

	useradd -m -u 1001 kubectluser
EOF

USER kubectluser
WORKDIR /home/kubectluser
