# syntax=docker/dockerfile:1.20.0

FROM --platform=${BUILDPLATFORM} ghcr.io/wiremind/base:hardened-systemd@sha256:40d2459e98bb2a4b9646b000e2d6c7af52b482f44864829647f3a5457f5691c1 AS builder

# hadolint ignore=DL3002
USER root
SHELL ["/bin/bash", "-exo", "pipefail", "-c"]

ARG UPSTREAM_TAG
RUN USE="static -pam" emerge -1 --root=/rootfs =sys-apps/busybox-${UPSTREAM_TAG}


FROM --platform=${BUILDPLATFORM} scratch

WORKDIR /
COPY --from=builder /rootfs/bin/busybox /busybox

ENTRYPOINT ["/busybox"]